version: "3.7"
services:

  db:
    image: oscarfonts/h2
    container_name: zeebe_db
    ports:
      - "1521:1521"
      - "81:81"

  zeebe:
    container_name: zeebe-test
    image: camunda/zeebe:latest
    ports:
      - "26500:26500"
    volumes:
      - "${PWD}/bpmn:/usr/local/zeebe/example"
      - "${PWD}/zeebe/zeebe-simple-monitor-exporter.jar:/usr/local/zeebe/lib/zeebe-simple-monitor-exporter.jar"
#      - "${PWD}/zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml"
    depends_on:
      - db

  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - spring.datasource.url=jdbc:h2:tcp://db:1521/zeebe-monitor
      - io.zeebe.monitor.connectionString=zeebe:26500
    ports:
      - "8080:8080"
    depends_on:
      - db
      - zeebe
